grpc:
  server:
    name: "banner"
    weight: 100
    addr: ":19093"
    etcdTTL: 60

redis:
  addr: "localhost:6379"

etcd:
  endpoints:
    - "localhost:12379"

mysql:
  dsn: "root:12345678@tcp(localhost:3306)/asynccnu"
